[package]
name = "advent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
num = "0.4.1"
petgraph = "0.6.4"
regex = "1.10.2"
threadpool = "1.8.1"
